services:
  - type: web_service
    name: urban-planning-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: "8000"
